SELECT DATEADD(DAY, 1, EOMONTH(DATEADD(MONTH, -1, GETDATE())))


--TASK 1
DECLARE @BIRTHDAY DATETIME
SET @BIRTHDAY = '1/1/2000'

SELECT (DATEDIFF(YEAR, @BIRTHDAY, GETDATE()) -
 CASE WHEN MONTH(@BIRTHDAY) >= MONTH(GETDATE()) OR DAY(@BIRTHDAY) > DAY(GETDATE()) THEN 1 ELSE 0 END ) as age

 DECLARE @BIRTHDAYY DATETIME
SET @BIRTHDAYY = '06/02/2000'

DECLARE @YEAR INT = (SELECT DATEDIFF(YEAR, @BIRTHDAYY, GETDATE()) -
 CASE WHEN MONTH(@BIRTHDAYY) > MONTH(GETDATE()) OR DAY(@BIRTHDAYY) >= DAY(GETDATE()) THEN 1 ELSE 0 END)
SET @BIRTHDAYY = DATEADD(YEAR, @YEAR, @BIRTHDAYY) 

DECLARE @MONTH INT = DATEDIFF(MONTH, @BIRTHDAYY, GETDATE()) - (CASE WHEN DAY(@BIRTHDAYY) > DAY(GETDATE()) THEN 1 ELSE 0 END)
SET @BIRTHDAYY = DATEADD(MONTH, @MONTH, @BIRTHDAYY)

DECLARE @DAY INT = DATEDIFF(DAY, @BIRTHDAYY, GETDATE())
SELECT @YEAR AS 'YEARS', @MONTH AS 'MONTHS', @DAY AS 'DAYS'



DECLARE @BIRTHDATE DATETIME = '2000-06-02' -- Tug'ilgan sana
DECLARE @TODAY DATETIME = GETDATE() -- Hozirgi sana

-- YILNI HISOBLASH
DECLARE @YEAR INT = DATEDIFF(YEAR, @BIRTHDATE, @TODAY) 
IF (MONTH(@BIRTHDATE) > MONTH(@TODAY)) OR 
   (MONTH(@BIRTHDATE) = MONTH(@TODAY) AND DAY(@BIRTHDATE) > DAY(@TODAY))
BEGIN
    SET @YEAR = @YEAR - 1
END

-- SHU YILGI TUG'ILGAN KUNNI ANIQLASH
DECLARE @LAST_BIRTHDAY DATE = DATEADD(YEAR, @YEAR, @BIRTHDATE)

-- OYLARNI HISOBLASH
DECLARE @MONTH INT = DATEDIFF(MONTH, @LAST_BIRTHDAY, @TODAY)
IF DAY(@LAST_BIRTHDAY) > DAY(@TODAY)
BEGIN
    SET @MONTH = @MONTH - 1
END

-- KUNLARNI HISOBLASH
DECLARE @DAY INT = DATEDIFF(DAY, DATEADD(MONTH, @MONTH, @LAST_BIRTHDAY), @TODAY)

-- NATIJA
SELECT @YEAR AS 'YEARS', @MONTH AS 'MONTHS', @DAY AS 'DAYS'

--Tug'ilgan yili, oyi, kuni, minuti va sekundini topish
DECLARE @Birth_date DATETIME
 SET @Birth_date = '09/25/1967 02:35:00'

 DECLARE @YEAR INT = (SELECT DATEDIFF(YEAR, @Birth_date, GETDATE()) -
         CASE WHEN MONTH(@Birth_date) > MONTH(GETDATE()) OR
		 (MONTH(@Birth_date) = MONTH(GETDATE()) AND 
		 DAY(@Birth_date) >= DAY(GETDATE())) THEN 1 ELSE 0 END)
		 SET @Birth_date = DATEADD(YEAR, @YEAR, @Birth_date)

DECLARE @MONTH INT = DATEDIFF(MONTH, @Birth_date, GETDATE()) - 
       (CASE WHEN DAY(@Birth_date) > DAY(GETDATE())THEN 1 ELSE 0 END)
	   SET @Birth_date = DATEADD(MONTH, @MONTH, @Birth_date)

DECLARE @DAY INT = DATEDIFF(DAY, @Birth_date, GETDATE())
        SET @Birth_date = DATEADD(DAY, @DAY, @Birth_date)

DECLARE @HOUR INT = DATEDIFF(HOUR, @Birth_date, GETDATE())
        SET @Birth_date = DATEADD(HOUR, @HOUR, @Birth_date)

DECLARE @MINUTE INT = DATEDIFF(MINUTE, @Birth_date, GETDATE())
        SET @Birth_date = DATEADD(MINUTE, @MINUTE, @Birth_date)

DECLARE @SECOND INT = DATEDIFF(SECOND, @Birth_date, GETDATE())
        SET @Birth_date = DATEADD(SECOND, @SECOND, @Birth_date)

SELECT @YEAR AS 'YEARS', @MONTH AS 'MONTHS', @DAY AS 'DAYS', @MINUTE AS 'MINUTES', @SECOND AS 'SECONDS'
        
